# Generated by Django 5.2.1 on 2025-05-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="creatd_at",
            new_name="created_at",
        ),
    ]
